import type { Metadata } from "next";
import "../styles/globals.css";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
import { AuthLifecycleProvider } from "@/providers/auth-lifecycle";
import { QueryProvider } from "@/providers/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthBootstrapProvider } from "@/providers/auth-context";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class" // adds class="dark" or class="light" to <html>
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <QueryProvider>
              <AuthBootstrapProvider>
                <AuthLifecycleProvider>{children}</AuthLifecycleProvider>
              </AuthBootstrapProvider>
            </QueryProvider>
          </ReduxProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
