import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
import { AuthInitializer } from "@/providers/auth-provider";
import { QueryProvider } from "@/providers/query-provider";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <QueryProvider>
            <AuthInitializer />
            {children}
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
